# Generated by Django 4.2.16 on 2024-11-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Unknown', max_length=255)),
                ('address', models.CharField(default='Unknown', max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=-160.0, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_co_nm', models.CharField(default='Unknown', max_length=255)),
                ('fin_prdt_cd', models.CharField(default='Unknown', max_length=255, unique=True)),
                ('fin_prdt_nm', models.CharField(default='Unknown', max_length=255)),
                ('join_way', models.CharField(default='-', max_length=255)),
                ('mtrt_int', models.TextField(default='-')),
                ('spcl_cnd', models.TextField(default='-')),
                ('join_deny', models.IntegerField(default=1)),
                ('join_member', models.TextField(default='실명의 개인')),
                ('etc_note', models.TextField(default='-')),
                ('fin_co_subm_day', models.CharField(default='000000000000', max_length=12)),
                ('max_limit', models.DecimalField(decimal_places=2, default=-1.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type_nm', models.CharField(default='Unknown', max_length=100)),
                ('save_trm', models.IntegerField(default=-1)),
                ('intr_rate', models.DecimalField(decimal_places=2, default=-1.0, max_digits=5)),
                ('intr_rate2', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rsrv_type_nm', models.CharField(default='Unknown', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='BankProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bank')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
