# Generated by Django 4.2.16 on 2024-11-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=-1.0, max_digits=15),
        ),
    ]
