# Generated by Django 4.2.16 on 2024-11-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_userproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='product_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('saving', 'Saving')], default='기타', max_length=50),
        ),
    ]
