# Generated by Django 4.2.16 on 2024-11-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_userproduct_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='etc_product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
