# Generated by Django 4.2.16 on 2024-11-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productoption_intr_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_limit',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='intr_rate',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=5),
        ),
    ]
