# Generated by Django 4.2.16 on 2024-11-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_max_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='etc_note',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fin_prdt_cd',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='join_way',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='mtrt_int',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spcl_cnd',
            field=models.TextField(default='Unknown'),
        ),
    ]
