# Generated by Django 4.2.16 on 2024-11-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_userproduct_etc_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='etc_product',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='product_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('saving', 'Saving'), ('etc', 'Etc')], default='etc', max_length=50),
        ),
    ]
