# Generated by Django 4.2.16 on 2024-11-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_etc_note_alter_product_fin_prdt_cd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fin_prdt_cd',
            field=models.CharField(default='Unknown', max_length=255, unique=True),
        ),
    ]
