# Generated by Django 4.2.16 on 2024-11-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_userproduct_etc_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
