# Generated by Django 4.2.16 on 2024-11-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_fin_prdt_cd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fin_prdt_cd',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
