# Generated by Django 4.2.16 on 2024-11-20 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_fin_prdt_cd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='join_way',
        ),
        migrations.CreateModel(
            name='JoinWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_ways', to='products.product')),
            ],
        ),
    ]
