# Generated by Django 4.2.16 on 2024-11-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_userproduct_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='balance',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
