# Generated by Django 4.2.16 on 2024-11-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_join_way_joinway'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bank_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bankproduct',
            old_name='bank_location',
            new_name='address',
        ),
    ]
