# Generated by Django 4.2.16 on 2024-11-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_userproduct_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='kor_co_nm',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
