# Generated by Django 4.2.16 on 2024-11-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_userproduct_fin_prdt_nm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='etc_product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='fin_prdt_nm',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='kor_co_nm',
            field=models.CharField(max_length=255),
        ),
    ]
