# Generated by Django 4.2.16 on 2024-11-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_userproduct_deposit_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='product_type',
            field=models.CharField(choices=[('deposit', '예금'), ('saving', '저축'), ('etc', '기타')], max_length=50),
        ),
    ]
