# Generated by Django 4.2.16 on 2024-11-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_userproduct_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='product_type',
            field=models.CharField(max_length=50),
        ),
    ]
