# Generated by Django 4.2.16 on 2024-11-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_userproduct_etc_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='end_date',
            field=models.DateField(blank=True, default='9999-99-99', null=True),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='start_date',
            field=models.DateField(blank=True, default='1111-11-11', null=True),
        ),
    ]
