# Generated by Django 4.2.16 on 2024-11-22 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_userproduct_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(9999, 12, 31)),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(1, 1, 1)),
        ),
    ]
