# Generated by Django 4.2.16 on 2024-11-24 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_userproduct_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2027, 11, 24)),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
