# Generated by Django 4.2.16 on 2024-11-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.CharField(max_length=10)),
                ('cur_nm', models.CharField(max_length=50)),
                ('ttb', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tts', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cur_to_krw', models.DecimalField(decimal_places=4, max_digits=12)),
                ('krw_to_cur', models.DecimalField(decimal_places=4, max_digits=12)),
                ('updated_at', models.DateField()),
            ],
        ),
    ]
