# Generated by Django 4.2.16 on 2024-11-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='request_date',
            new_name='updated_at',
        ),
    ]
