# Generated by Django 4.2.17 on 2024-12-22 18:03

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('nickname', models.CharField(max_length=10)),
                ('fullname', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(default='profile_images/default.png', upload_to='profile_images/')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('남', 'Male'), ('여', 'Female')], max_length=10)),
                ('birth_date', models.DateField(blank=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_expense', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_mydata_consent', models.BooleanField(default=False)),
                ('job', models.CharField(blank=True, choices=[('직장인', 'Office Worker'), ('자영업자', 'Self-Employed'), ('학생', 'Student'), ('무직', 'Unemployed'), ('기타', 'Other')], max_length=50, null=True, verbose_name='직업')),
                ('category_choice', models.IntegerField(blank=True, choices=[(1, '정액적립식 복리'), (2, '자유적립식 단리'), (3, '정기예금 단리'), (4, '정기예금 복리')], null=True, verbose_name='관심 카테고리')),
                ('has_main_bank', models.BooleanField(blank=True, null=True, verbose_name='주거래 은행 여부')),
                ('change_bank', models.BooleanField(blank=True, null=True, verbose_name='주거래 은행 변경 의향')),
                ('max_contract_months', models.IntegerField(blank=True, null=True, verbose_name='최대 계약 기간 (개월)')),
                ('interest_in_event', models.BooleanField(blank=True, null=True, verbose_name='이벤트 상품 관심 여부')),
                ('deposit_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='정기예금 최소 금액')),
                ('deposit_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='정기예금 최대 금액')),
                ('saving_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='정기적금 최소 금액')),
                ('saving_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='정기적금 최대 금액')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
