# Generated by Django 4.2.17 on 2024-12-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category_choice',
            field=models.IntegerField(blank=True, choices=[(1, '정액적립식 복리'), (2, '자유적립식 단리'), (3, '정기예금 단리'), (4, '정기예금 복리')], null=True, verbose_name='관심 카테고리'),
        ),
    ]
