# Generated by Django 4.2.17 on 2024-12-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_category_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job',
            field=models.CharField(blank=True, choices=[('직장인', 'Office Worker'), ('자영업자', 'Self-Employed'), ('학생', 'Student'), ('무직', 'Unemployed'), ('기타', 'Other')], max_length=50, null=True, verbose_name='직업'),
        ),
    ]
