# Generated by Django 4.2.16 on 2024-11-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_assets',
            field=models.IntegerField(default=0),
        ),
    ]
