# Generated by Django 4.2.16 on 2024-11-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
