# Generated by Django 4.2.16 on 2024-11-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_total_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('남', 'Male'), ('여', 'Female')], max_length=10),
        ),
    ]
