# Generated by Django 4.2.16 on 2024-11-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='nickname_tmp', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
