# Generated by Django 4.2.16 on 2024-11-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='monthly_expense',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='monthly_income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_assets',
            field=models.IntegerField(),
        ),
    ]
